### ISSUE TITLE
No known class method for selector 'darkTheme' @ RNBraintreeDropIn.m:16

### ISSUE THREAD

**Issue by iosvanyd1** [wgltony/react-native-braintree-dropin-ui#34]
I am getting the following error on Xcode during the compilation process on line 16: `No known class method for selector 'darkTheme'`. And another one on line 40.
<img width="1027" alt="Screen Shot 2020-02-18 at 8 10 11 PM" src="https://user-images.githubusercontent.com/24326834/74792205-bbec2000-528a-11ea-9a65-c694c04878e0.png">

**Comment by JavanHuang** [comment]
Hi @iosvanyd1, the `darkTheme` property has been depecrated in [Remove Deprecated Methods and Properties #206](https://github.com/braintree/braintree-ios-drop-in/pull/206) and I have raised a pull request to fix it.

The fix would be to use `BTUIKAppearance.sharedInstance.colorScheme` instead of BTUIKAppearance darkTheme` and set it accordingly based on the iOS version.

```   
if([options[@"darkTheme"] boolValue]){
    if (@available(iOS 13.0, *)) {
        BTUIKAppearance.sharedInstance.colorScheme = BTUIKColorSchemeDynamic;
    } else {
        BTUIKAppearance.sharedInstance.colorScheme = BTUIKColorSchemeDark;
    }
} else {
        BTUIKAppearance.sharedInstance.colorScheme = BTUIKColorSchemeLight;
    }
```
